### ISSUE TITLE
how to run>

### ISSUE THREAD

**Issue by elinaroz** [zurutech/anomaly-toolbox#6]
is it possible to describe the implementation of the code?

i run this 
pip install anomaly-toolbox

in colab it show this error

ERROR: Could not find a version that satisfies the requirement anomaly-toolbox (from versions: none)
ERROR: No matching distribution found for anomaly-toolbox

**Comment by iLeW** [comment]
Hello @elinaroz. Unfortunately, Google Colab runs (today, 21 Feb 2022) on `Python 3.7.12`. To be able to correctly run the `anomaly-toolbox` on Colab, we suggest you to run these commands first:

```bash
!apt-get install python3.8
!update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1
!update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 2
!apt install python3-pip
!curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
!python3 get-pip.py --force-reinstall
!pip install anomaly-toolbox
```
You can ignore the warning asking you to restart the Colab runtime. 

The above instructions are meant to install Python 3.8 (the minimum required version for `anomaly-toolbox` to run) and correctly re-install `pip`. Please, be aware that we did not test the whole functioning of the toolbox on Colab, but the above instructions should do the trick. Let us know if there are any other problems. 

Regarding the implementation description of the code, what exactly do you need? In the meantime, if it can be of any help, our code implements `GANomaly`, `EGBAD (BiGAN)`, `AnoGAN`, and `DeScarGAN` works. You can find the reference to these works in the `Reference` section of the main `README`.

**Comment by elinaroz** [comment]
Thanks On 21 Feb 2022 13:13, Federico ***@***.***> wrote:
Hello @elinaroz. Unfortunately, Google Colab runs (today, 21 Feb 2022) on Python 3.7.12. To be able to correctly run the anomaly-toolbox on Colab, we suggest you to run this commands first:
!apt-get install python3.8
!update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1
!update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 2
!apt install python3-pip
!curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
!python3 get-pip.py --force-reinstall
!pip install anomaly-toolbox
You can ignore the warning asking you to restart the Colab runtime.
The above instructions are meant to install Python 3.8 (the minimum required version for anomaly-toolbox to run) and correctly re-install pip. Please, be aware that we did not test the whole functioning of the toolbox on Colab, but the above instructions should do the trick. Let us know if there are any other problems.
Regarding the implementation description of the code, what exactly do you need? In the meantime, if it can be of any help, our code implements GANomaly, EGBAD (BiGAN), AnoGAN, and DeScarGAN works. You can find the reference to these works in the Reference section of the main README.

**Comment by iLeW** [comment]
Hi @elinaroz,

Thank you for your feedback and for confirming that the provided solution worked for you. Since there have been no further issues reported and your query appears to be resolved, I will proceed to close this issue.
